angular.module 'angular'
  .config ($logProvider, toastrConfig, $authProvider) ->
    'ngInject'
    # Enable log
    $logProvider.debugEnabled true
    # Set options third-party lib
    toastrConfig.allowHtml = true
    toastrConfig.timeOut = 3000
    toastrConfig.positionClass = 'toast-top-right'
    toastrConfig.preventDuplicates = true
    toastrConfig.progressBar = true

    $authProvider.configure
      apiUrl: '/api/v1'
      tokenValidationPath: '/auth/validate_token'
      signOutUrl: '/auth/sign_out'
      emailRegistrationPath: '/auth'
      accountUpdatePath: '/auth'
      accountDeletePath: '/auth'
      confirmationSuccessUrl: window.location.href
      passwordResetPath: '/auth/password'
      passwordUpdatePath: '/auth/password'
      passwordResetSuccessUrl: window.location.href
      emailSignInPath: '/auth/sign_in'
      storage: 'cookies'
      forceValidateToken: false
      validateOnPageLoad: true
      proxyIf: ->
        false
      proxyUrl: '/proxy'
      omniauthWindowType: 'sameWindow'
      authProviderPaths:
        github: '/auth/github'
        facebook: '/auth/facebook'
        google: '/auth/google'
      tokenFormat:
        'access-token': '{{ token }}'
        'token-type': 'Bearer'
        'client': '{{ clientId }}'
        'expiry': '{{ expiry }}'
        'uid': '{{ uid }}'
      cookieOps:
        path: '/'
        expires: 9999
        expirationUnit: 'days'
        secure: false
        domain: 'domain.com'
      createPopup: (url) ->
        window.open url, '_blank', 'closebuttoncaption=Cancel'
      parseExpiry: (headers) ->
        # convert from UTC ruby (seconds) to UTC js (milliseconds)
        parseInt(headers['expiry']) * 1000 or null
      handleLoginResponse: (response) ->
        response.data
      handleAccountUpdateResponse: (response) ->
        response.data
      handleTokenValidationResponse: (response) ->
        response.data

# ---
# generated by js2coffee 2.2.0
